name: steamcmd
version: git
summary: Command-line interface for Steam
description: |
  The Steam Console Client or SteamCMD is acommand-line version of the Steam client.
  Its primary use is to install and update various dedicated servers available on Steamusing a command-line interface. 
base: core18
confinement: devmode
grade: devel

apps:
  steamcmd:
    command: steamcmd.sh

parts:
  steamcmd:
    plugin: dump
    source: .
    build-packages:
      - lib32gcc1
    # This override is needed to bootstrap the initial "update" steamcmd does at first run
    override-prime: |
      snapcraftctl prime
      /root/parts/steamcmd/install/steamcmd.sh validate +quit 
    stage:
      - steamcmd.sh
      - linux32/
    prime:
      - steamcmd.sh
      - linux32/